# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GjTJ07pWlhrVyxvaF09hnNJXQ2zHbbWu
"""

from fastapi import FastAPI, File, UploadFile
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image
import io

from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="MNIST CNN API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)



# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model
model = torch.load("cnn_mnist_full_model.pth", map_location=device)
model.eval()

# Transform (same as training)
transform = transforms.Compose([
    transforms.Grayscale(),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# Root endpoint
@app.get("/")
def home():
    return {"message": "MNIST CNN API is running 🚀"}

# Prediction endpoint
@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    try:
        # Read image
        image_bytes = await file.read()
        image = Image.open(io.BytesIO(image_bytes))

        # Preprocess
        image = transform(image).unsqueeze(0).to(device)

        # Prediction
        with torch.no_grad():
            outputs = model(image)
            _, predicted = torch.max(outputs, 1)

        return {
            "prediction": int(predicted.item())
        }

    except Exception as e:
        return {"error": str(e)}